admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

pig:
    resource: "@PIGBundle/Resources/config/routing.yml"
    prefix:   /pig

fct:
    resource: "@fctBundle/Resources/config/routing.yml"
    prefix:   /

landing:
    resource: "@landingBundle/Resources/config/routing.yml"
    prefix:   /landing

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: "user/logout"
