# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        fctBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        all_users:
            chain:
                providers: [db_users, in_memory]

        db_users:
            entity:
                class: fctBundle:User
                property: username
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            http_basic: ~
        user:
            pattern: ^/user
            anonymous: ~
            provider: db_users
            form_login:
                login_path: /user/login
                check_path: /user/login
                default_target_path: /user
            logout:
                  path:   /user/logout
                  target: /user
        main:
          anonymous: ~

    access_control:
            - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user, roles: ROLE_USER }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/user/admin, roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
