<?php

namespace PIGBundle\Repository;

/**
 * TrabajadoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajadoraRepository extends \Doctrine\ORM\EntityRepository
{
}
